@startuml

!pragma layout smetana
!define STDLIB https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master
!include STDLIB/awslib/AWSCommon.puml
!include STDLIB/awslib/AWSSimplified.puml
!include STDLIB/awslib/General/all.puml
!include STDLIB/awslib/GroupIcons/all.puml
!include STDLIB/awslib/Storage/all.puml
!include STDLIB/awslib/Analytics/all.puml

skinparam linetype polyline

rectangle awscloud <<awscloud>> as "<color:AWS_COLOR><$Cloudalt></color> <color:grey>AWS CLOUD</color>" {

    SimpleStorageService(s3DataLakeSource, "S3 Data Lake Source", "")
    User(dataAnalyst, "Data Analyst", "")
    Athena(athena, "Amazon Athena", "")

    rectangle awsglue <<awsglue>> as "<color:#6A40C1><$Glue></color> AWS Glue" {
        GlueCrawler(glueCrawler, "Crawler", "")
        GlueDataCatalog(glueDataCatalog, "Data Catalog", "")
    }

    s3DataLakeSource -r--> glueCrawler
    glueCrawler -r--> glueDataCatalog
    athena -r-> glueDataCatalog
    dataAnalyst -d-> athena : Analyze

}

@enduml